### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by changliao1025** [sahrk/DGGRID#78] opened 2024-07-02 02:13 UTC
dggrid/compile/DGGRID-master/src/lib/dglib/lib/DgZ3RF.cpp:104:24: error: expected ')' before 'PRIx64'
  104 |    if (!sscanf(tok, "%" PRIx64, &val))

g++ --version
g++ (conda-forge gcc 12.3.0-13) 12.3.0

**Comment by sahrk** [comment] 2024-07-07 00:52
@changliao1025 I think I know what the problem is and have pushed a fix to the `master` branch. But I can't be sure without setting up a test environment to reproduce your error. So please give the new `master` a try and let me know whether or not it does the trick.

**Comment by changliao1025** [comment] 2024-07-07 18:06
It appears this affects more than this h/cpp. I have to add the following code in at least three header files to fix them.

#define __STDC_FORMAT_MACROS 1 //added by Chang Liao
#include <cinttypes> #use c++ header

I put them in the header instead of the source, and I only used the C++ header as I found if both C++ and C headers are present, the compiling fails, too.

**Comment by sahrk** [comment] 2024-07-07 18:47
That is the line that I added to three header files in the current `master`. Are you saying it needs to be added to another three files? Can you confirm whether or not the current `master` fixes your problem?

**Comment by changliao1025** [comment] 2024-07-09 18:04
'PRIx64' shows up in 'DgZOrder.cpp', 'DgZOrderStringRF.cpp', 'DgZ3RF.cpp', 'DgZ3StringRF.cpp. So I need to add the fix into them all. 
After that, the error is gone.

**Comment by sahrk** [comment] 2024-07-09 21:42
I added it to the `.h` files, so I think it should be fixed in `master` now.

**Closed by sahrk** 2024-07-09 21:42 UTC
